version: '3.8'

services:

  mysql:
    image: mysql:innovation
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: turnos
    ports:
      - "9010:3306"